# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: coskuntekin @ frontend developer
email: mail@coskuntekin.com
description: >- # this means to ignore newlines until "baseurl:"
  I write stuff about HTML5, CSS3, Web API, jQuery, AngularJS, Angular,
  Vue.js, Middleman, Jekyll.
  Ruby on Rails, focused on front-end development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coskuntekin.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: coskuntekin
github_username: coskuntekin

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
sass:
  quiet_deps: true
  verbose: false
  style: compressed
  load_paths:
    - _sass
    - node_modules

# Plugins
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
